version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.development
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -b '0.0.0.0' -p 3000"
    ports:
      - "3000:3000"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
